### ISSUE TITLE
Didn't load link for full schema yaml file

### ISSUE THREAD

**Issue by mtvenD** [marcelthole/openapi-merge#26]
I need to merge my schemas.yaml into the main file at `components: schemas`.

Error message and first trace line:
```
{
    "class": "cebe\\openapi\\exceptions\\TypeErrorException",
    "message": "Unable to instantiate cebe\\openapi\\spec\\Schema Object with data 'schemas.yaml' at ",
    "trace":
        [
           {
             "file": "/Users/faks/dev/Sites/site/vendor/cebe/php-openapi/src/SpecBaseObject.php",
             "line": 124,
             "function": "instantiate", 
             "class": "cebe\\openapi\\SpecBaseObject",
             "type": "->", 
             "args": ["cebe\\openapi\\spec\\Schema","schemas.yaml"]
          }
         [...]
      ]
}
```

My doc
api.yaml (main file)
```
[...]
components:
    schemas:
        $ref: "schemas.yaml"
[...]
```
schemas.yaml
```
FirstSchema:
    [...]
SecondSchema:
    [...]
```

**Comment by marcelthole** [comment]
Hi
this could be a issue because the `api.yml` is not a valid OpenAPI Structure.
I assume you are using OpenAPI 3.0.x? 

Here is the Documentation for the Components Object: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#componentsObject

in the `schemas` is no `$ref` allowed to include other files.
> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

If you want the Schemas as `$ref` you could use them directly in the Document and don't need to define them in the main api.yml File. The final result will not contain the Components.

For Example:
```yml 
# api.yml
openapi: "3.0.2"
info:
  version: "1"
  title: "Issue 26"
paths:
  /ping:
    get:
      requestBody:
        $ref: "schemas.yml#/components/schemas/FirstSchema"
```
```yml
# schemas.yml
openapi: "3.0.2"
info:
  version: "1"
  title: "Issue 26"
paths: { }
components:
  schemas:
    FirstSchema:
      title: FirstSchema
      type: string
    SecondSchema:
      title: SecondSchema
      type: string

```

Result:
```yml
# php bin/openapi-merge api.yml schemas.yml
openapi: 3.0.2
info:
  title: 'Issue 26'
  version: '1'
paths:
  /ping:
    get:
      requestBody:
        title: FirstSchema
        type: string
components:
  schemas: []
```

**Comment by mtvenD** [comment]
Thank you very much for the answer. Yes, it really isn't possible to use a separate file for `schemas` and `$ref` to it in the main file. Looks like I've seen the `node.js` package do it but didn't pay attention to the spec. Thanks!
