### ISSUE TITLE
symphony 7

### ISSUE THREAD

**Issue by RolandVerner** [marcelthole/openapi-merge#42]
Hello the main package on what this Is base on not even updates more like 2 years [cebe/php-openapi](https://github.com/cebe/php-openapi)
I can't install this package cause of php 8.3 and symphony 6 which is in the main package

**Comment by marcelthole** [comment]
Hello,
yeah i know, sadly there are no updates since a few months. The are already a lot of working PR to solve these issues and some other forks already.
You could see it here: https://github.com/cebe/php-openapi/pull/203 for Symfony7 and https://github.com/cebe/php-openapi/issues/190 as overall status of the further library maintenance.

Maybe it's time to fork cebe/php-openapi with a group to get the latest updates again

**Comment by RolandVerner** [comment]
https://github.com/DEVizzent/cebe-php-openapi
I saw that people already make something like this

> Hello, yeah i know, sadly there are no updates since a few months. The are already a lot of working PR to solve these issues and some other forks already. You could see it here: [cebe/php-openapi#203](https://github.com/cebe/php-openapi/pull/203) for Symfony7 and [cebe/php-openapi#190](https://github.com/cebe/php-openapi/issues/190) as overall status of the further library maintenance.
> 
> Maybe it's time to fork cebe/php-openapi with a group to get the latest updates again

**Comment by marcelthole** [comment]
Hey, 
i forked the core repository from cebe and updated the dependencies and also changed the core implementation of this library to https://github.com/openapi-php/php-openapi

This allows us now to use symfony 7 :)
